name: No. 9 Farms
favicon: null
layout_spectrum: 0.2958787695970386
typography_spectrum: 0.4376490181311965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ea3d7'
    - '#bec8d4'
    - '#65764a'
    - '#374538'
    - '#bd9f71'
  brandStrength: 0
  lightness: 0.41559826442971826
  saturation: 0.0625
  rhythmicContrast: 0.5841034215409309
purpose: []
